const constants =  {
  SET_PRODUCTS: "SET_PRODUCTS",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  SET_CART: "SET_CART",
  TOGGLE_PRODUCT_LIKE: "TOGGLE_PRODUCT_LIKE",
  SET_LIKE_PRODUCTS: "SET_LIKE_PRODUCTS",
  SET_PRODUCTS_FILTER: "SET_PRODUCTS_FILTER",
  ALL: "ALL",
  SHOW_LIKED: "SHOW_LIKED"
}

module.exports = Object.freeze(constants);